// Generated by insterra

module "aws_bucket_blackeye_uea" {
  source  = "upmaru/instellar/aws//modules/bucket"
  version = "0.9.5"

  blueprint  = var.identifier
  identifier = "blackeye-uea"
  region     = var.aws_region
}
